version: "3"

services:
  # customer-db:
  #   container_name: customer-db
  #   image: mysql/mysql-server
  #   ports:
  #     - "3306:33060"
  #   environment:
  #       MYSQL_DATABASE: customer
  #       MYSQL_USER: user
  #       MYSQL_PASSWORD: test
  #       MYSQL_ROOT_PASSWORD: newpassword

  # customer:
  #   build: customer/.
  #   image: customer:latest
  #   container_name: customer
  #   depends_on:
  #     customer-db:
  #       condition: service_healthy
  #   ports:
  #     - "9091:9091"

  # order:
  #   build: order/.
  #   image: order:latest
  #   container_name: order
  #   depends_on: 
  #     db2:
  #       condition: service_healthy
  #   ports:
  #     - "9090:9090"
  product:
    image: prod:latest
    container_name: product
    depends_on: 
      product-db:
        condition: service_healthy
    ports:
      - "9090:9090"
    environment:
        USER: user
        PWD: test
        APP_PORT: 9090

  # order-db:
  #   container_name: order-db
  #   image: mysql/mysql-server
  #   ports:
  #     - "3307:33060"
  #   environment:
  #       MYSQL_DATABASE: orders
  #       MYSQL_USER: user
  #       MYSQL_PASSWORD: test
  #       MYSQL_ROOT_PASSWORD: newpassword

  product-db:
    container_name: product-db
    image: mysql/mysql-server
    ports:
      - "3308:33060"
    environment:
        MYSQL_DATABASE: product
        MYSQL_USER: user
        MYSQL_PASSWORD: test
        MYSQL_ROOT_PASSWORD: newpassword
