---
apiVersion: v1
kind: Service
metadata:
  name: customer
spec:
  ports:
    - protocol: TCP
      port: 9292
      targetPort: 9292
  selector:
    app: customer
---
apiVersion: v1
kind: ServiceAccount
metadata:
  name: customer
automountServiceAccountToken: true
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: customer
spec:
  replicas: 1
  selector:
    matchLabels:
      service: customer
      app: customer
  template:
    metadata:
      labels:
        service: customer
        app: customer
      annotations:
        "consul.hashicorp.com/connect-inject": 'true'
        "consul.hashicorp.com/connect-service-upstreams": "customer-mysql:3307"
    spec:
      serviceAccountName: customer
      containers:
        - name: customer
          image: localhost:5000/customer/k8s:latest
          ports:
            - containerPort: 9292
          env:
            - name: USER
              value: user
            - name: PWD
              value: test
            - name: APP_PORT
              value: "9292"