---
apiVersion: v1
kind: Service
metadata:
  name: order
  labels:
    app: order
spec:
  ports:
    - protocol: TCP
      port: 9191
      targetPort: 9191
  selector:
    app: order
---
apiVersion: v1
kind: ServiceAccount
metadata:
  name: order
automountServiceAccountToken: true
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: order
spec:
  replicas: 1
  selector:
    matchLabels:
      service: order
      app: order
  template:
    metadata:
      labels:
        service: order
        app: order
      annotations:
        "consul.hashicorp.com/connect-inject": 'true'
        "consul.hashicorp.com/connect-service-upstreams": "order-mysql:3305"
    spec:
      serviceAccountName: order
      containers:
        - name: order
          image: deep21/order:latest
          ports:
            - containerPort: 9191
          env:
            - name: USER
              value: user
            - name: PWD
              value: test
            - name: APP_PORT
              value: "9191"