global:
 enabled: true
 name: consul
 datacenter: dc1
 tls:
   enabled: true
server:
 enabled: true
 replicas: 1
ui:
 enabled: true
 service:
   type: NodePort
connectInject:
 enabled: true
controller:
  enabled: true
